apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  labels:
    app: grafana

spec:
  replicas: 2
  selector:
    matchLabels:
       app: grafana
  template:
    metadata:
      name: graf-deploy
      labels:
        app: grafana
    spec:
      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: grafana-pvc
      containers:
        - name: grafana
          image: anurag08/graf:v1
          imagePullPolicy: IfNotPresent
          volumeMounts: 
           - mountPath: "/var/lib/grafana"
             name: grafana-storage
         
      restartPolicy: Always
  
